spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authservice_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Decembrie2001
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.format_sql: true

    show-sql: true



server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8080


application:
  jwt:
    secretKey: asdasdasdasdasd123344asdasdasdasdasasd12321332sadas
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 7

